import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import "@testing-library/jest-dom";
import LandingPage from "../components/landingPage/LandingPage";

// Generated by Qodo Gen

describe("LandingPage", () => {
  // Component renders with main heading 'PLAN & LAYOUT YOUR EVENT'
  it("should display the main heading text", () => {
    render(<LandingPage />);

    const heading = screen.getByText(/PLAN & LAYOUT YOUR EVENT/i);

    expect(heading).toBeInTheDocument();
  });
});
